replicaCount: 3
# heapSize: 1024
# dataLogDir: "/zk/logs"
commonLabels: 
  name: zookeeper
resources:
  limits: 
    memory: 4096Mi
    cpu: 500m
  requests:
    memory: 4096Mi
    cpu: 500m
nodeSelector:
  app: rss    
    
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - zookeeper
      topologyKey: "kubernetes.io/hostname"