alertmanager:
  enabled: false
kubeApiServer:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubelet:
  enabled: false  
kubeScheduler:
  enabled: false          
grafana:
  enabled: false

prometheus:
  serviceAccount:
    create: true
    name: amp-iamproxy-ingest-service-account
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::{ACCOUNTID}:role/{EKSCLUSTER_NAME}-prometheus-ingest
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 15s
    remoteWrite:
    - url: https://aps-workspaces.{AWS_REGION}.amazonaws.com/workspaces/{WORKSPACE_ID}/api/v1/remote_write
      sigv4:
        region: {AWS_REGION}
      queueConfig:
        maxSamplesPerSend: 3000
        batchSendDeadline: 10s
        minShards: 4
        maxShards: 200
        capacity: 10000
      
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false