apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-headless
{{- if .Values.postgres.service.annotations }}
  annotations:
{{ toYaml .Values.postgres.service.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "ranger.name" . }}
    chart: {{ template "ranger.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "ranger.name" . }}
    release: {{ .Release.Name }}